# Generated by Django 4.2.27 on 2026-02-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(blank=True, help_text='e.g. Waterfall, Cafe, Beach', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Wiki-style description')),
                ('how_to_reach', models.TextField(blank=True)),
                ('best_time_to_visit', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('instagram_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('original_url', models.URLField(max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('raw_caption', models.TextField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('comments_dump', models.JSONField(blank=True, default=list, null=True)),
                ('author_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('instagram_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='ReelFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frames/')),
                ('timestamp', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='core.scrapedreel')),
            ],
        ),
        migrations.CreateModel(
            name='LocationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_snapshot', models.JSONField(help_text='Stores the full description/meta at the time of edit')),
                ('edited_by', models.CharField(default='Anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(help_text='What was changed?', max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.location')),
            ],
        ),
    ]
