# Generated by Django 4.2.27 on 2026-01-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('instagram_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('original_url', models.URLField(max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='reel/')),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('raw_caption', models.TextField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('comments_dump', models.JSONField(blank=True, default=list)),
                ('author_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('instagram_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
