# Generated by Django 4.2.27 on 2026-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='extracted_tips',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
