# Generated by Django 4.2.27 on 2026-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedreel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
