# Generated by Django 4.2.27 on 2026-01-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_scrapedreel_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedreel',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.CreateModel(
            name='ReelFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frames/')),
                ('timestamp', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='core.scrapedreel')),
            ],
        ),
    ]
