# Generated by Django 4.2.27 on 2026-02-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scrapedreel_audio_file_reelframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedreel',
            name='comments_dump',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
