# Generated by Django 4.2.27 on 2026-03-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_district_specific_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='best_time_to_visit',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='extracted_tips',
        ),
        migrations.RemoveField(
            model_name='location',
            name='how_to_reach',
        ),
        migrations.AddField(
            model_name='location',
            name='general_info',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic subjective info and vibes'),
        ),
        migrations.AddField(
            model_name='location',
            name='known_facts',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic objective data points'),
        ),
    ]
