# Generated by Django 4.2.27 on 2026-03-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_location_best_time_to_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nearby_places',
            field=models.JSONField(blank=True, default=list, help_text="List of nearby places: [{'name': '...', 'type': '...', 'distance': '...'}]"),
        ),
    ]
