# Generated by Django 4.2.27 on 2026-03-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_location_alternate_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedreel',
            name='extracted_general_info',
            field=models.JSONField(blank=True, default=dict, help_text='Subjective info strictly from this reel'),
        ),
        migrations.AddField(
            model_name='scrapedreel',
            name='extracted_known_facts',
            field=models.JSONField(blank=True, default=dict, help_text='Objective facts strictly from this reel'),
        ),
    ]
