# Generated by Django 4.2.27 on 2026-03-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_scrapedreel_extracted_general_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedreel',
            name='extracted_general_info',
            field=models.JSONField(blank=True, default=dict, help_text='Subjective info strictly from this reel', null=True),
        ),
        migrations.AlterField(
            model_name='scrapedreel',
            name='extracted_known_facts',
            field=models.JSONField(blank=True, default=dict, help_text='Objective facts strictly from this reel', null=True),
        ),
    ]
