# Generated by Django 4.2.27 on 2026-03-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_scrapedreel_extracted_general_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedreel',
            name='comments_dump',
            field=models.JSONField(blank=True, default=list, help_text="Schema: [{'text': '...', 'likes': 0, 'date': '...'}]", null=True),
        ),
    ]
