# Generated by Django 4.2.27 on 2026-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_scrapedreel_comments_dump"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedreel",
            name="extracted_district",
            field=models.CharField(
                blank=True,
                help_text="District inferred for this reel from caption/audio/comments",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scrapedreel",
            name="extracted_specific_area",
            field=models.CharField(
                blank=True,
                help_text="Specific area/locality inferred for this reel from caption/audio/comments",
                max_length=150,
                null=True,
            ),
        ),
    ]
